"""오케스트레이션: 주제(topic)와 무관한 코드. topic_id별로 갈라지는 로직이 전혀 없다 —
새 주제를 추가할 때 이 파일은 절대 수정하지 않는다."""

import asyncio
import json
from pathlib import Path

from . import db
from .image_compose import compose_card, compose_cta_card
from .image_gen import generate_card_background
from .schemas import RESEARCH_SCHEMA, STORYBOARD_SCHEMA
from .sdk_client import run_structured_query
from .topics.base import TopicConfig

RUNS_DIR = Path(__file__).resolve().parent.parent / "data" / "runs"


async def run_research_stage(run_id: str, topic: TopicConfig) -> None:
    row = db.get_run(run_id)
    source_text = row.get("source_text") if row else None
    db.append_event(run_id, "stage_start", f"AI 조사 시작 (topic={topic.topic_id}, tools={topic.tools})")
    result = await run_structured_query(
        topic.research_prompt(source_text),
        RESEARCH_SCHEMA,
        model=topic.research_model,
        tools=topic.tools,
    )
    if not result.ok:
        db.update_run(
            run_id,
            status="failed",
            error_message=result.error,
            research_session_id=result.session_id,
        )
        db.append_event(run_id, "stage_failed", f"조사 실패: {result.error}")
        return

    candidates = result.data.get("candidates", [])
    db.update_run(
        run_id,
        status="waiting_for_user",
        stage="await_selection",
        research_session_id=result.session_id,
        candidates_json=json.dumps(result.data),
    )
    db.append_event(run_id, "stage_done", f"후보 {len(candidates)}개 조사 완료 — 사용자 선택 대기")


def _verification_prompt(
    topic: TopicConfig,
    selected: list[dict],
    source_text: str | None = None,
    notes: str | None = None,
) -> str:
    lo, hi = topic.storyboard_card_range
    listing = "\n".join(
        f"- candidate_id={c['candidate_id']}: {c['title']} ({c['date']}, {c['source_url']})"
        for c in selected
    )
    if source_text:
        # source_text 토픽: "후보"는 원고를 나누는 분할안이다. 검증은 웹 검색이 아니라
        # "카드 문구가 원문에 실제로 있는 내용인가"를 스스로 대조하는 것으로 의미가 바뀐다.
        base = (
            f"Here is the original article:\n\n---\n{source_text}\n---\n\n"
            f"The user picked this division plan:\n{listing}\n\n"
            "Using that division plan, draft the actual card text now. For EACH card, list which "
            "sentences/ideas from the ORIGINAL ARTICLE it is based on as confirmed_facts, and list "
            "anything you added that is NOT literally in the original article as unconfirmed_claims "
            "(there should be none — if you find yourself adding unconfirmed_claims, rewrite the card "
            "to stay within the original article's content instead). Use evidence_url to quote the "
            "exact original sentence(s) each card draws from (not a URL — just quote the source text).\n\n"
            f"Then produce the final storyboard: exactly {lo if lo == hi else f'{lo} to {hi}'} cards, "
            "each with a headline, body text (a faithful excerpt or tight paraphrase of the original — "
            "do not invent new content), a description of what the image should show (image_role, in "
            "English, describing a concrete visual metaphor from the article), and which part of the "
            "article it draws from (source). Also produce a 200-character Instagram caption "
            "summarizing the whole article, and up to 15 relevant hashtags, in the top-level 'caption' "
            "and 'hashtags' fields."
        )
        if topic.cta_card:
            base += (
                f"\n\nThe LAST card (card_number={hi}) must be a call-to-action card, not a content "
                "card: its headline/body should invite the reader to read the full article (mention "
                "that the full version is available), and its image_role should just say "
                "'call-to-action card — no illustration needed' (the actual visual will be a QR code, "
                "handled separately, not generated by you)."
            )
    else:
        base = (
            f"The user selected the following candidates:\n{listing}\n\n"
            "For EACH selected candidate, verify its claims by reading the source (and other "
            "corroborating sources if useful) via WebFetch/WebSearch. Separate confirmed_facts "
            "(directly supported by a source you can cite) from unconfirmed_claims (stated but not "
            "independently verified). List the evidence_url(s) you actually checked.\n\n"
            f"Then draft a card-news storyboard with {lo} to {hi} cards. Each card needs a headline, "
            "body text, a short description of what the image should show (image_role), and which "
            "candidate/source it draws from. Base every card only on confirmed_facts — if a candidate "
            "could not be verified (confirmed_facts is empty), do not build a card from it, and say so "
            "in that candidate's verification entry instead of inventing content."
        )
    if topic.output_language == "ko":
        base += (
            "\n\nWrite the headline and body of every storyboard card in Korean (한국어). "
            "Keep candidate_id and evidence_url values as-is (do not translate URLs/IDs)."
        )
    if notes:
        base += f"\n\nThe user requested this revision to the previous storyboard: {notes}"
    return base


async def run_verification_stage(run_id: str, topic: TopicConfig) -> None:
    row = db.get_run(run_id)
    if row is None:
        return
    candidates = (row.get("candidates") or {}).get("candidates", [])
    selected_ids = set(row.get("selected_candidates") or [])
    selected = [c for c in candidates if c["candidate_id"] in selected_ids]

    db.append_event(run_id, "stage_start", f"심층 검증 + 스토리보드 작성 시작 ({len(selected)}개 후보)")
    result = await run_structured_query(
        _verification_prompt(topic, selected, source_text=row.get("source_text")),
        STORYBOARD_SCHEMA,
        model=topic.verification_model,
        resume=row.get("research_session_id"),
        tools=topic.tools,
    )
    if not result.ok:
        db.update_run(run_id, status="failed", error_message=result.error)
        db.append_event(run_id, "stage_failed", f"검증/스토리보드 실패: {result.error}")
        return

    db.update_run(
        run_id,
        status="waiting_for_user",
        stage="await_approval",
        storyboard_session_id=result.session_id,
        verification_json=json.dumps(result.data),
    )
    card_count = len(result.data.get("storyboard", []))
    db.append_event(run_id, "stage_done", f"스토리보드 {card_count}장 작성 완료 — 사용자 승인 대기")


async def run_revision_stage(run_id: str, topic: TopicConfig, notes: str | None) -> None:
    row = db.get_run(run_id)
    if row is None:
        return
    candidates = (row.get("candidates") or {}).get("candidates", [])
    selected_ids = set(row.get("selected_candidates") or [])
    selected = [c for c in candidates if c["candidate_id"] in selected_ids]

    history = row.get("revision_notes") or []
    history.append(notes or "")

    db.append_event(run_id, "stage_start", f"수정 요청 반영 중: {notes or '(내용 없음)'}")
    result = await run_structured_query(
        _verification_prompt(topic, selected, source_text=row.get("source_text"), notes=notes),
        STORYBOARD_SCHEMA,
        model=topic.verification_model,
        resume=row.get("storyboard_session_id") or row.get("research_session_id"),
        tools=topic.tools,
    )
    if not result.ok:
        db.update_run(run_id, status="failed", error_message=result.error, revision_notes_json=json.dumps(history))
        db.append_event(run_id, "stage_failed", f"수정 반영 실패: {result.error}")
        return

    db.update_run(
        run_id,
        status="waiting_for_user",
        stage="await_approval",
        storyboard_session_id=result.session_id,
        verification_json=json.dumps(result.data),
        revision_notes_json=json.dumps(history),
    )
    db.append_event(run_id, "stage_done", "수정된 스토리보드 작성 완료 — 사용자 승인 대기")


def _image_prompt(topic: TopicConfig, card: dict) -> str:
    return f"{topic.image_style_guidance}. {card['image_role']}"


async def _generate_one_card(
    run_dir: Path, topic: TopicConfig, card: dict, source_url: str | None = None
) -> dict:
    n = card["card_number"]
    record = {
        "card_number": n,
        "headline": card["headline"],
        "body": card["body"],
        "bg_path": None,
        "final_path": None,
        "status": "pending",
        "error": None,
    }
    is_cta_card = topic.cta_card and n == topic.storyboard_card_range[1]
    try:
        final_path = run_dir / f"card_{n}_final.png"
        if is_cta_card:
            if not source_url:
                raise RuntimeError("cta_card 토픽인데 source_url이 없습니다.")
            # QR+URL 안내 카드는 사진이 필요 없으므로 OpenAI를 호출하지 않는다
            # (DJ 체크리스트 3번: 필요한 만큼만 쓴다).
            await asyncio.to_thread(
                compose_cta_card, card["headline"], card["body"], source_url, str(final_path)
            )
            record.update(final_path=str(final_path), status="ok")
        else:
            bg_bytes = await asyncio.to_thread(
                generate_card_background, _image_prompt(topic, card), quality=topic.image_quality
            )
            bg_path = run_dir / f"card_{n}_bg.png"
            bg_path.write_bytes(bg_bytes)
            await asyncio.to_thread(compose_card, bg_bytes, card["headline"], card["body"], str(final_path))
            record.update(bg_path=str(bg_path), final_path=str(final_path), status="ok")
    except Exception as e:  # noqa: BLE001 — 카드 단위 실패는 여기서 잡아서 기록하고 다음 카드로 넘어간다
        record.update(status="failed", error=str(e))
    return record


async def run_image_generation_stage(run_id: str, topic: TopicConfig) -> None:
    row = db.get_run(run_id)
    if row is None:
        return
    storyboard = (row.get("verification") or {}).get("storyboard", [])
    run_dir = RUNS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    db.append_event(run_id, "stage_start", f"카드 {len(storyboard)}장 이미지 생성 시작")
    records: list[dict] = []
    for card in storyboard:
        record = await _generate_one_card(run_dir, topic, card, source_url=row.get("source_url"))
        records.append(record)
        # DJ 체크리스트 7번: 카드 하나가 실패해도 전체를 버리지 않는다. 매 카드마다
        # 즉시 저장해두면, 도중에 서버가 죽어도 이미 만든 카드는 남는다.
        db.update_run(run_id, images_json=json.dumps(records))
        if record["status"] == "ok":
            db.append_event(run_id, "tool_call", f"카드 {record['card_number']} 이미지 생성 성공")
        else:
            db.append_event(run_id, "tool_call_failed", f"카드 {record['card_number']} 이미지 생성 실패: {record['error']}")

    db.update_run(run_id, status="waiting_for_user", stage="await_review")
    ok_count = sum(1 for r in records if r["status"] == "ok")
    db.append_event(run_id, "stage_done", f"이미지 생성 완료 ({ok_count}/{len(records)}장 성공) — 사용자 검수 대기")


async def run_single_card_image(run_id: str, topic: TopicConfig, card_number: int) -> None:
    row = db.get_run(run_id)
    if row is None:
        return
    storyboard = (row.get("verification") or {}).get("storyboard", [])
    card = next((c for c in storyboard if c["card_number"] == card_number), None)
    if card is None:
        db.update_run(run_id, status="waiting_for_user")
        return

    run_dir = RUNS_DIR / run_id
    run_dir.mkdir(parents=True, exist_ok=True)
    record = await _generate_one_card(run_dir, topic, card, source_url=row.get("source_url"))

    images = [r for r in (row.get("images") or []) if r["card_number"] != card_number]
    images.append(record)
    images.sort(key=lambda r: r["card_number"])
    db.update_run(run_id, status="waiting_for_user", stage="await_review", images_json=json.dumps(images))
    if record["status"] == "ok":
        db.append_event(run_id, "tool_call", f"카드 {card_number} 재생성 성공")
    else:
        db.append_event(run_id, "tool_call_failed", f"카드 {card_number} 재생성 실패: {record['error']}")
